[package]
name = "hello_world"
version = "0.1.0"
authors = ["as-potehin <piroteh2006@yandex.ru>"]
edition = "2018"

[dependencies]
library = { git = "https://github.com/kartrez/hw_library.git", version = "0.1.0" }